version: 1

models:
  - name: stg_people
    description: "Fact table relating to the characters in the films"
    columns:
      - name: resource_url
        description: "the hypermedia URL of this resource, also acts as primary key"
        tests:
          - unique
          - not_null
      - name: character_name
        description: "The name of this person."
      - name: height
        description: "The height of the person in centimeters."
      - name: mass
        description: "The mass of the person in kilograms."
      - name: hair_color
        description: "The hair color of this person. Will be 'unknown' if not known or 'n/a' if the person does not have hair."
      - name: skin_color
        description: "The skin color of this person."
      - name: eye_color
        description: "The eye color of this person. Will be 'unknown' if not known or 'n/a' if the person does not have an eye."
      - name: birth_year
        description: "The birth year of the person, using the in-universe standard of BBY or ABY - Before the Battle of Yavin or After the Battle of Yavin. The Battle of Yavin is a battle that occurs at the end of Star Wars episode IV: A New Hope."
      - name: gender
        description: "The gender of this person. Either 'Male', 'Female' or 'unknown', 'n/a' if the person does not have a gender."
      - name: species
        description: "An array of species resource URLs that this person belongs to."

  - name: stg_errata_people
    description: "Fact table relating to the characters in the films"
    columns:
      - name: resource_url
        description: "the hypermedia URL of the relevant character, also acts as primary key"
      - name: character_name
        description: "The name of this person."
      - name: species_url
        description: "A species resource URL that this person belongs to."

  - name: stg_films
    description: "Dimension table about the different movies"
    columns:
      - name: film_url
        description: "the hypermedia URL of this resource, also acts as primary key"
        tests:
          - unique
          - not_null
      - name: title
        description: "The title of this film"
      - name: episode_id
        description: "The episode number of this film."
      - name: opening_crawl
        description: "The opening paragraphs at the beginning of this film."
      - name: director
        description: "The name of the director of this film."
      - name: producer
        description: "The name(s) of the producer(s) of this film. Comma separated."
      - name: release_date
        description: "The ISO 8601 date format of film release at original creator country."
      - name: characters
        description: " An array of people resource URLs that are in this film."
      - name: planets
        description: "An array of planet resource URLs that are in this film."
      - name: starships
        description: "An array of starship resource URLs that are in this film."
      - name: vehicles
        description: "An array of vehicle resource URLs that are in this film."
      - name: species
        description: "An array of species resource URLs that are in this film."

  - name: stg_species
    description: "Dimension table about the different species present in the movies"
    columns:
      - name: resource_url
        description: "the hypermedia URL of this resource, also acts as primary key"
        tests:
          - unique
          - not_null
      - name: species_name
        description: "The name of this species."
      - name: classification
        description: "The classification of this species, such as 'mammal' or 'reptile'."
      - name: designation
        description: "The designation of this species, such as 'sentient'."
      - name: average_height
        description: "The average height of this species in centimeters."
      - name: skin_colors
        description: "A comma-separated string of common skin colors for this species, 'none' if this species does not typically have skin."
      - name: hair_colors
        description: "A comma-separated string of common hair colors for this species, 'none' if this species does not typically have hair."
      - name: eye_colors
        description: "A comma-separated string of common eye colors for this species, 'none' if this species does not typically have eyes."
      - name: average_lifespan
        description: "The average lifespan of this species in years."
      - name: language
        description: "The language commonly spoken by this species."
      - name: homeworld
        description: "The URL of a planet resource, a planet that this species originates from."
      - name: people
        description: "An array of People URL Resources that are a part of this species."
      - name: films
        description: "An array of Film URL Resources that this species has appeared in."